# SwaggerUI doesn't support 3.1.0 yet...
# In other words, leave this error alone
openapi: 3.0.0
info:
  version: 1.0.0
  title: Sample API
  description: A sample API to illustrate OpenAPI concepts
paths:
  /api/Metadata/GetInstalledOrgs:
    get:
      operationId: getInstalledOrgs
      description: Returns a list of all GitHub Organizations where this app is installed
      tags:
        - metadata
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OrgModel"
  /api/Metadata/GetRateLimitsForOrg/{installationId}:
    get:
      operationId: getCurrentRateLimit
      description: Gets the current rate limit information for the specified org
      tags:
        - metadata
      parameters:
        - in: path
          name: installationId
          schema:
            type: number
          required: true
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Limits"
  /api/sync/SynchronizeOrg:
    post:
      operationId: syncOrg
      description: Triggers a synchronization job for the specified org
      tags:
        - sync
      parameters:
        - in: query
          name: installationId
          schema:
            type: array
            items:
              type: number
          required: true
      responses:
        "200":
          description: A successful response
  /api/orchestrator:
    post:
      operationId: syncAllOrgs
      description: Triggers a synchronization job for all orgs
      tags:
        - sync
      responses:
        "200":
          description: A successful response
components:
  schemas:
    OrgModel:
      type: object
      properties:
        id:
          type: number
        orgName:
          type: string
      required:
        - id
        - orgName
    Limits:
      type: object
      properties:
        remaining:
          type: number
      required:
        - remaining
