openapi: 3.1.0
info:
  version: 1.0.0
  title: Sample API
  description: A sample API to illustrate OpenAPI concepts
paths:
  /api/Metadata/GetInstalledOrgs:
    get:
      operationId: getInstalledOrgs
      description: Returns a list of all GitHub Organizations where this app is installed              
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: "#/components/schemas/OrgModel"
components:
  schemas:
    OrgModel:
      type: object
      properties:
        id:
          type: number
        orgName:
          type: string
      required:
      - id
      - orgName