# SwaggerUI doesn't support 3.1.0 yet...
# In other words, leave this error alone
openapi: 3.0.0
info:
  version: 1.0.0
  title: Sample API
  description: A sample API to illustrate OpenAPI concepts
paths:
  /api/Metadata/GetInstalledOrgs:
    get:
      operationId: getInstalledOrgs
      description: Returns a list of all GitHub Organizations where this app is installed  
      tags:
      - metadata            
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: "#/components/schemas/OrgModel"
  /api/Metadata/GetRateLimitsForOrg/{orgId}:
    get:
      operationId: getCurrentRateLimit
      description: Gets the current rate limit information for the specified org
      tags:
      - metadata
      parameters:
      - in: path
        name: orgId
        schema:
          type: number
        required: true
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Limits"
components:
  schemas:
    OrgModel:
      type: object
      properties:
        id:
          type: number
        orgName:
          type: string
      required:
      - id
      - orgName
    Limits:
      type: object
      properties:
        remaining:
          type: number
      required:
      - remaining